[package]
name = "libparted"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
libc = "*"
libparted-sys = { git = "https://github.com/system76/libparted-sys.git" }

[dev-dependencies]
libc = "*"
failure = "0.1"
failure_derive = "0.1"
